bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.14")
bazel_dep(name = "googletest", version = "1.17.0.bcr.1")
bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "rules_cc_resources", version = "0.3.0")
bazel_dep(name = "rules_foreign_cc", version = "0.15.1")
bazel_dep(name = "opencv-mobile-luckfox", version = "0.1.0")
bazel_dep(name = "stb", version = "0.0.0-20251026-f1c79c0")
bazel_dep(name = "cc_toolchains_linux", version = "0.0.1")

include("//:override.MODULE.bazel")

cc_configure = use_extension("@rules_cc//cc:extensions.bzl", "cc_configure_extension")
use_repo(cc_configure, "local_config_cc")

register_execution_platforms(
    "@platforms//host:host",
    "@cc_toolchains_linux//:linux-x86_64",
    "@cc_toolchains_linux//:linux-armv7l-luckfox",
)

register_toolchains(
    "@cc_toolchains_linux//:linux-x86_64-toolchain",
    "@cc_toolchains_linux//:linux-armv7l-luckfox-toolchain",
)

include("//third-party:repositories.MODULE.bazel")
